-- AlterTable
ALTER TABLE "UserEducation" ALTER COLUMN "startYear" SET DATA TYPE TEXT,
ALTER COLUMN "endYear" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "UserWork" ALTER COLUMN "startYear" SET DATA TYPE TEXT,
ALTER COLUMN "endYear" SET DATA TYPE TEXT;
